language: node_js

node_js:
  - "6"

addons:
  postgresql: "9.3"

before_script:
  - yarn global add mocha coffee-script knex
  - psql -c 'create database chatter;' -U postgres
  - knex migrate:latest
  - knex seed:run

script:
  npm test
